# Generated by Django 6.0.2 on 2026-02-10 13:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_member_delete_reason'),
        ('recruitment', '0003_rating_reg_date_rating_reservation_id_and_more'),
        ('reservation', '0006_reservation_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='reg_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rating',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(condition=models.Q(('reservation_id__isnull', False)), fields=('member_id', 'reservation_id'), name='unique_rating_per_reservation'),
        ),
    ]
